services:
  - type: static
    name: react-expense-tracker
    env: node
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install -f && npm run build
    publishPath: build
    autoDeploy: true
